Repository beclab/Olares, pull requests merged in 2024-07, with the labels that each got.

#171 feat: update wise and knowledge version
  apps/knowledge/config/user/helm-charts/knowledge/templates/knowledge_deployment.yaml
  apps/rss/config/cluster/deploy/rss_deploy.yaml
  apps/wise/config/user/helm-charts/wise/templates/wise_deployment.yaml
Labels: feat

#172 feat: update knowledge env
  apps/knowledge/config/user/helm-charts/knowledge/templates/knowledge_deployment.yaml
Labels: feat

#173 ci: bump to 1.7.0
  .github/workflows/check.yaml
  .github/workflows/release-daily.yaml
  build/installer/version.hint
Labels: ci

#174 feat: support raspbian arm64 version
  build/installer/install_cmd.sh
  build/manifest/images
Labels: feat

#175 fix: velero update, add wait-minute
  build/installer/install_cmd.sh
  build/installer/uninstall_cmd.sh
  build/manifest/dependencies.amd64
  build/manifest/dependencies.arm64
Labels: fix

#179 feat: difyfusion relative changes
  apps/files/config/user/helm-charts/files/templates/files_deploy.yaml
  apps/nitro/config/cluster/deploy/dify_deploy.yaml
  apps/nitro/config/cluster/deploy/nitro_deploy.yaml
  apps/nitro/config/user/helm-charts/dify/.helmignore
  apps/nitro/config/user/helm-charts/dify/Chart.yaml
  apps/nitro/config/user/helm-charts/dify/templates/NOTES.txt
  apps/nitro/config/user/helm-charts/dify/templates/_helpers.tpl
  apps/nitro/config/user/helm-charts/dify/templates/dify_fe_deploy.yaml
  apps/nitro/config/user/helm-charts/dify/values.yaml
  frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
Labels: feat

#180 feat: support WSL2 Ubuntu-22.04 in Windows 11
  build/installer/install_cmd.sh
Labels: feat

#181 feat: add media server for files
  apps/files/config/user/helm-charts/files/templates/files_deploy.yaml
Labels: feat

#182 feat: File supports video
  apps/files/config/user/helm-charts/files/templates/files_deploy.yaml
Labels: feat

#183 refactor: legacy api with envoy sidecar
  frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
  frameworks/system-server/config/user/helm-charts/systemserver/templates/systemserver_deploy.yaml
Labels: refactor

#184 feat: restore dify model auto config
  apps/nitro/config/cluster/deploy/nitro_deploy.yaml
Labels: feat

#185 feat: support adding arm64 worker node
  build/installer/install_cmd.sh
  build/installer/publicAddnode.sh
  build/manifest/images.node.mf
  scripts/image-manifest.sh
Labels: feat

#186 feat: update market to v0.2.8
  apps/market/config/user/helm-charts/market/templates/market_deploy.yaml
Labels: feat

#187 feat: add api intent v2 provider registry
  apps/desktop/config/user/helm-charts/desktop/templates/desktop_deploy.yaml
Labels: feat

#188 feat: update profile version to v0.3.23
  apps/profile/config/user/helm-charts/profile/templates/profile_deployment.yaml
Labels: feat

#189 feat: update profile version to v0.3.23
  apps/profile/config/user/helm-charts/profile/templates/profile_deployment.yaml
Labels: feat

#190 feat: update market to v0.2.8
  apps/market/config/user/helm-charts/market/templates/market_deploy.yaml
Labels: feat

#191 feat: difyfusion relative changes
  apps/files/config/user/helm-charts/files/templates/files_deploy.yaml
  apps/nitro/config/cluster/deploy/dify_deploy.yaml
  apps/nitro/config/cluster/deploy/nitro_deploy.yaml
  apps/nitro/config/user/helm-charts/dify/.helmignore
  apps/nitro/config/user/helm-charts/dify/Chart.yaml
  apps/nitro/config/user/helm-charts/dify/templates/NOTES.txt
  apps/nitro/config/user/helm-charts/dify/templates/_helpers.tpl
  apps/nitro/config/user/helm-charts/dify/templates/dify_fe_deploy.yaml
  apps/nitro/config/user/helm-charts/dify/values.yaml
  frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
Labels: feat

#193 chore: optimize controlhub and dashboard build configuration
  apps/system-apps/config/user/helm-charts/monitoring/templates/monitoring_deploy.yaml
  apps/system-apps/config/user/helm-charts/system/templates/admin_console_deploy.yaml
Labels: chore

#194 fix: support raspbian & bump k3s to 1.22.16
  build/installer/install_cmd.sh
  build/manifest/images
Labels: fix

#196 chore: optimize controlhub and dashboard build configuration
  apps/system-apps/config/user/helm-charts/monitoring/templates/monitoring_deploy.yaml
  apps/system-apps/config/user/helm-charts/system/templates/admin_console_deploy.yaml
Labels: chore

#195 feat: support adding arm64 worker node
  build/installer/install_cmd.sh
  build/installer/publicAddnode.sh
  build/manifest/images.node.mf
  scripts/image-manifest.sh
Labels: feat

#198 fix: nitro nginx config spell error
  apps/nitro/config/cluster/deploy/nitro_deploy.yaml
Labels: fix

#199 fix: nitro nginx config spell error
  apps/nitro/config/cluster/deploy/nitro_deploy.yaml
Labels: fix

#200 ci: add macos installation script to installer package
  scripts/package.sh
Labels: ci

#203 feat: update build for quasar.config
  apps/desktop/config/user/helm-charts/desktop/templates/desktop_deploy.yaml
  apps/wizard/config/user/helm-charts/wizard/templates/wizard_deploy.yaml
  third-party/authelia/config/user/helm-charts/auth/templates/auth_deploy.yaml
Labels: feat

#204 feat: add postgres extension zhparser
  frameworks/tapr/config/cluster/deploy/citus_deployment.yaml
Labels: feat

#205 fix: delete ControlHub/Middleware/ZincSearch
  apps/system-apps/config/user/helm-charts/system/templates/admin_console_deploy.yaml
Labels: fix

#208 fix: for special characters in path
  apps/files/config/user/helm-charts/files/templates/files_deploy.yaml
Labels: fix

#202 feat: update build for quasar.config
  apps/desktop/config/user/helm-charts/desktop/templates/desktop_deploy.yaml
  apps/wizard/config/user/helm-charts/wizard/templates/wizard_deploy.yaml
  third-party/authelia/config/user/helm-charts/auth/templates/auth_deploy.yaml
Labels: feat

#207 feat: files remove zinc and dify-gateway provider call
  apps/files/config/user/helm-charts/files/templates/files_deploy.yaml
Labels: feat

#210 fix: installing bugs on macos
  scripts/developer/install_macos.sh
Labels: fix

#209 fix: installing bugs on macos
  scripts/developer/install_macos.sh
Labels: fix

#211 feat: support open id connect
  frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
  frameworks/bfl/config/launcher/templates/bfl_deploy.yaml
  third-party/authelia/config/cluster/deploy/auth_backend_deploy.yaml
Labels: feat

#212 feat: Revert "feat: files remove zinc and dify-gateway provider call (#207)"
  apps/files/config/user/helm-charts/files/templates/files_deploy.yaml
Labels: feat

#213 fix: app inter call sidecar inject;update vectors to 0.3.0
  frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
  frameworks/system-server/config/user/helm-charts/systemserver/templates/systemserver_deploy.yaml
  frameworks/tapr/config/cluster/deploy/citus_deployment.yaml
Labels: fix

#214 feat: add download module
  apps/download/.DS_Store
  apps/download/README.md
  apps/download/config/user/helm-charts/.DS_Store
  apps/download/config/user/helm-charts/download/.DS_Store
  apps/download/config/user/helm-charts/download/.helmignore
  apps/download/config/user/helm-charts/download/Chart.yaml
  apps/download/config/user/helm-charts/download/templates/download_deploy.yaml
  apps/download/config/user/helm-charts/download/values.yaml
  apps/knowledge/config/user/helm-charts/knowledge/templates/knowledge_deployment.yaml
Labels: feat

#215 feat: remove knowledge zinc
  apps/knowledge/config/user/helm-charts/knowledge/templates/knowledge_deployment.yaml
Labels: feat

#216 fix: download env
  apps/knowledge/config/user/helm-charts/knowledge/templates/knowledge_deployment.yaml
Labels: fix

#217 feat: remove zinc server from terminus
  apps/system-apps/config/user/helm-charts/monitoring/templates/monitoring_deploy.yaml
  frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
  frameworks/system-server/config/user/helm-charts/systemserver/templates/systemserver_deploy.yaml
  frameworks/tapr/config/cluster/deploy/middleware_deploy.yaml
  frameworks/tapr/config/cluster/deploy/zincserver_deploy.yaml
  frameworks/tapr/config/user/helm-charts/zinc/.helmignore
  frameworks/tapr/config/user/helm-charts/zinc/Chart.yaml
  frameworks/tapr/config/user/helm-charts/zinc/templates/NOTES.txt
  frameworks/tapr/config/user/helm-charts/zinc/templates/_helpers.tpl
  frameworks/tapr/config/user/helm-charts/zinc/templates/zinc_deploy.yaml
  frameworks/tapr/config/user/helm-charts/zinc/values.yaml
Labels: feat

#220 fix: fix knowledge auto restart
  apps/knowledge/config/user/helm-charts/knowledge/templates/knowledge_deployment.yaml
Labels: fix

#221 feat: quick install script for macos & wsl & Raspberry Pi
  .github/workflows/release-daily.yaml
  .github/workflows/upload-full.yaml
  build/installer/install.sh
  build/installer/publicInstaller.latest
Labels: feat

#218 docs: update home cloud as project positioning
  README.md
Labels: docs

#219 feat: update market to version v0.2.9
  apps/market/config/user/helm-charts/market/templates/market_deploy.yaml
Labels: feat

#222 fix: Optimize the memory usage of media-server
  apps/files/config/user/helm-charts/files/templates/files_deploy.yaml
Labels: fix

#223 fix: change ip for wsl
  build/installer/change_ip.sh
Labels: fix

#224 fix: os arch check for macos
  build/installer/change_ip.sh
  build/installer/install.sh
  build/installer/install_cmd.sh
  build/installer/publicAddnode.sh
  build/installer/publicInstaller.latest
  build/installer/uninstall_cmd.sh
Labels: fix

#225 fix: downloading the wrong package
  build/installer/install.sh
  build/installer/publicInstaller.latest
Labels: fix

#226 docs: adjust readme message for home cloud positioning and other updates
  README.md
Labels: docs

#229 feat: quick install script for macos & wsl & Raspberry Pi
  .github/workflows/release-daily.yaml
  .github/workflows/release.yaml
  .github/workflows/upload-full.yaml
  build/installer/change_ip.sh
  build/installer/install.sh
  build/installer/install_cmd.sh
  build/installer/publicAddnode.sh
  build/installer/publicInstaller.latest
  build/installer/uninstall_cmd.sh
  build/manifest/images
Labels: feat

#230 fix: installing bug on wsl in release 1.6
  build/installer/install_cmd.sh
Labels: fix

#233 feat: Modify the quick installation script to resolve the issue of du…
  build/installer/install.sh
  build/installer/publicInstaller.latest
  build/installer/uninstall_cmd.sh
Labels: feat

#227 docs: further fix Web3 related wording and other formatting issues
  README.md
Labels: docs

#234 feat: Modify the quick installation script to resolve the issue of du…
  build/installer/install.sh
  build/installer/publicInstaller.latest
  build/installer/uninstall_cmd.sh
Labels: feat

#231 fix: fix dashboard layout bug in windows
  apps/system-apps/config/user/helm-charts/monitoring/templates/monitoring_deploy.yaml
Labels: fix

#235 feat: update market version to v0.2.10
  apps/market/config/user/helm-charts/market/templates/market_deploy.yaml
Labels: feat

#236 feat: update market version to v0.2.10
  apps/market/config/user/helm-charts/market/templates/market_deploy.yaml
Labels: feat

#237 feat: add controlhub/storages
  apps/system-apps/config/user/helm-charts/system/templates/admin_console_deploy.yaml
Labels: feat

#228 feat: init search3
  apps/search3/README.md
  apps/search3/config/cluster/deploy/search3_server_deploy.yaml
Labels: feat

#239 feat: Added initial support for Google Drive and Dropbox in Files.
  apps/files/config/user/helm-charts/files/templates/files_deploy.yaml
Labels: feat

#238 feat: Added a script to check the size of all images in the installation package.
  build/installer/check_image_size.sh
Labels: feat

#241 fix: fix knowledge corrunption auto restart in release-1.6
  apps/knowledge/config/user/helm-charts/knowledge/templates/knowledge_deployment.yaml
Labels: fix

#243 feat: 1.support content_language,title_language update 2.add meta fie…
  apps/search3/config/cluster/deploy/search3_server_deploy.yaml
Labels: feat

#240 fix: add velero create crds retries
  build/installer/install_cmd.sh
  build/manifest/dependencies.amd64
  build/manifest/dependencies.arm64
  build/manifest/images
Labels: fix

#245 feat: add options for set envoy outbound and inbound timeout
  frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
Labels: feat

#248 feat: update desktop&login&settings bg pictures
  apps/desktop/config/user/helm-charts/desktop/templates/desktop_deploy.yaml
  apps/settings/config/user/helm-charts/settings/templates/settings_deploy.yaml
  third-party/authelia/config/user/helm-charts/auth/templates/auth_deploy.yaml
Labels: feat

#247 feat: installation optimize
  build/installer/install_cmd.sh
  build/installer/uninstall_cmd.sh
  build/installer/wizard/config/account/templates/account.yaml
  frameworks/bfl/config/launcher/templates/bfl_deploy.yaml
  scripts/developer/install_macos.sh
  third-party/authelia/config/cluster/deploy/auth_backend_deploy.yaml
Labels: feat

#249 feat: installation optimize
  build/installer/change_ip.sh
  build/installer/install_cmd.sh
  build/manifest/images
  libs/fs-lib/config/cluster/deploy/fsnotify_daemon.yaml
Labels: feat

#250 feat: 1. add library entry to search pg 2. add get resource by uri router
  apps/knowledge/config/user/helm-charts/knowledge/templates/knowledge_deployment.yaml
  apps/search3/config/cluster/deploy/search3_server_deploy.yaml
Labels: feat

#251 fix: video-only media, 301 urlencode
  apps/files/config/user/helm-charts/files/templates/files_deploy.yaml
Labels: fix

#252 fix: check raspberry
  build/installer/install_cmd.sh
Labels: fix

#254 feat: add explicit runtime class for nvidia to support wsl
  build/installer/deploy/device-plugin.yaml
  build/installer/deploy/nvidia-device-plugin.yml
  build/installer/deploy/nvshare-system-quotas.yaml
  build/installer/deploy/nvshare-system.yaml
  build/installer/deploy/scheduler.yaml
  build/installer/install_cmd.sh
  frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
Labels: feat

#253 feat: update files version to v1.2.14
  apps/files/config/user/helm-charts/files/templates/files_deploy.yaml
  apps/vault/config/cluster/deploy/vault_server_deploy.yaml
  apps/vault/config/user/helm-charts/vault/templates/vault_deploy.yaml
Labels: feat

#255 fix: installing gpu bugs on wsl
  build/installer/install_cmd.sh
  build/manifest/images
Labels: fix

#256 feat: system-server proxy add support for sse/x-ndjson
  frameworks/system-server/config/user/helm-charts/systemserver/templates/systemserver_deploy.yaml
Labels: feat

#259 feat: files to os-system
  apps/files/config/cluster/deploy/files_deploy.yaml
  apps/files/config/user/helm-charts/files/templates/files_fe_deploy.yaml
Labels: feat

#258 feat: add controlhub/jobs and controlhub/browse/pod monitoring
  apps/system-apps/config/user/helm-charts/system/templates/admin_console_deploy.yaml
Labels: feat

#261 fix: apt update failed with wrong clock time
  build/installer/install_cmd.sh
Labels: fix

#260 feat: support gdrive and dropbox drive
  apps/files/config/user/helm-charts/files/templates/files_fe_deploy.yaml
  apps/settings/config/user/helm-charts/settings/templates/settings_deploy.yaml
  apps/vault/config/cluster/deploy/vault_server_deploy.yaml
  apps/vault/config/user/helm-charts/vault/templates/vault_deploy.yaml
Labels: feat

#262 feat: support minikube
  build/installer/install_cmd.sh
  build/installer/install_macos.sh
  build/installer/uninstall_macos.sh
  build/manifest/images
  scripts/build.sh
  scripts/developer/cluster-configuration.yaml
  scripts/developer/kubesphere-installer.yaml
  scripts/package.sh
Labels: feat

#263 fix: move media-server to os-system namespace
  apps/files/config/cluster/deploy/files_deploy.yaml
  apps/files/config/user/helm-charts/files/templates/files_fe_deploy.yaml
Labels: fix

#265 feat: 1.knowledge submit entry to search, using pure content extracte…
  apps/knowledge/config/user/helm-charts/knowledge/templates/knowledge_deployment.yaml
  apps/search3/config/cluster/deploy/search3_server_deploy.yaml
Labels: feat

#267 feat: get provider registry list by appname
  apps/files/config/user/helm-charts/files/templates/files_fe_deploy.yaml
  apps/market/config/user/helm-charts/market/templates/market_deploy.yaml
  apps/vault/config/user/helm-charts/vault/templates/vault_deploy.yaml
  frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
  frameworks/bfl/config/launcher/templates/bfl_deploy.yaml
  third-party/infisical/config/user/helm-charts/infisical/templates/infisical_deploy.yaml
Labels: feat

#264 feat: support switching jfsnotify to fsnotify
  apps/files/config/cluster/deploy/files_deploy.yaml
  build/installer/deploy/device-plugin.yaml
  build/installer/deploy/scheduler.yaml
  build/installer/install_cmd.sh
  build/installer/install_macos.sh
Labels: feat

#268 feat: update settings application providers and permissons
  apps/settings/config/user/helm-charts/settings/templates/settings_deploy.yaml
Labels: feat

#269 fix: files_os_system bugs
  apps/files/config/cluster/deploy/files_deploy.yaml
Labels: fix

#266 fix: ntpdate error
  build/installer/install_cmd.sh
Labels: fix

#270 fix: modify l4 imagePullPolicy
  build/manifest/images
  frameworks/bfl/config/launcher/templates/bfl_deploy.yaml
Labels: fix

#271 fix: optimize the os restart process
  apps/desktop/config/user/helm-charts/desktop/templates/desktop_deploy.yaml
  apps/download/config/user/helm-charts/download/templates/download_deploy.yaml
  apps/files/config/user/helm-charts/files/templates/files_fe_deploy.yaml
  apps/knowledge/config/user/helm-charts/knowledge/templates/knowledge_deployment.yaml
  apps/market/config/user/helm-charts/market/templates/market_deploy.yaml
  apps/notifications/config/user/helm-charts/notification/templates/notification_deploy.yaml
  apps/profile/config/user/helm-charts/profile/templates/profile_deployment.yaml
  apps/settings/config/user/helm-charts/settings/templates/settings_deploy.yaml
  apps/system-apps/config/user/helm-charts/monitoring/templates/monitoring_deploy.yaml
  apps/system-apps/config/user/helm-charts/system/templates/admin_console_deploy.yaml
  apps/vault/config/user/helm-charts/vault/templates/vault_deploy.yaml
  apps/wise/config/user/helm-charts/wise/templates/wise_deployment.yaml
  build/installer/deploy/device-plugin.yaml
  build/installer/deploy/scheduler.yaml
  build/installer/install_cmd.sh
  build/manifest/images
  third-party/headscale/config/user/helm-charts/headscale/templates/headscale_deploy.yaml
  third-party/infisical/config/user/helm-charts/infisical/templates/infisical_deploy.yaml
Labels: fix

#272 fix: minikube install
  build/installer/install_macos.sh
Labels: fix

#273 fix: hide pvc in play path, service bug
  apps/files/config/cluster/deploy/files_deploy.yaml
Labels: fix

#274 fix: upgrade installer
  build/installer/install_macos.sh
Labels: fix

#275 feat: support playing videos in Data and Cache
  apps/files/config/cluster/deploy/files_deploy.yaml
Labels: feat

#276 feat: add knowledge download
  apps/download/config/user/helm-charts/download/templates/download_deploy.yaml
  apps/knowledge/config/user/helm-charts/knowledge/templates/knowledge_deployment.yaml
  apps/wise/config/user/helm-charts/wise/templates/wise_deployment.yaml
Labels: feat

#278 feat: files_1.7
  apps/files/config/user/helm-charts/files/templates/files_fe_deploy.yaml
  apps/vault/config/cluster/deploy/vault_server_deploy.yaml
  apps/vault/config/user/helm-charts/vault/templates/vault_deploy.yaml
Labels: feat

#277 fix: fix controlhub/jobs job actions
  apps/system-apps/config/user/helm-charts/system/templates/admin_console_deploy.yaml
Labels: fix

#279 ci: bump to 1.8.0
  .github/workflows/check.yaml
  .github/workflows/release-daily.yaml
  build/installer/version.hint
Labels: ci
