Repository beclab/Olares, pull requests merged in 2024-09, with the labels that each got.

#406 feat: zfs support
  build/installer/install.sh
  build/installer/install_cmd.sh
  build/installer/install_macos.sh
  build/installer/publicInstaller.latest
  build/installer/uninstall_cmd.sh
  build/installer/uninstall_macos.sh
Labels: feat

#407 feat: add cookie upload page
  apps/files/config/user/helm-charts/files/templates/files_fe_deploy.yaml
  apps/vault/config/cluster/deploy/vault_server_deploy.yaml
  apps/vault/config/user/helm-charts/vault/templates/vault_deploy.yaml
Labels: feat

#408 feat: add cookie legacy provider
  apps/settings/config/user/helm-charts/settings/templates/settings_deploy.yaml
Labels: feat

#409 feat: download add cookie
  apps/download/config/user/helm-charts/download/templates/download_deploy.yaml
  apps/knowledge/config/user/helm-charts/knowledge/templates/knowledge_deployment.yaml
Labels: feat

#410 feat: files only watches drive while not watching Data, Cache and External
  apps/files/config/cluster/deploy/files_deploy.yaml
Labels: feat

#411 feat: disable nitro for the time being
  apps/nitro/config/cluster/deploy/nitro_deploy.yaml
Labels: feat

#412 docs: remove Proxmox from the comparison table
  README.md
  README_CN.md
Labels: docs

#414 feat: release market v0.2.14
  apps/market/config/user/helm-charts/market/templates/market_deploy.yaml
Labels: feat

#415 feat: bfl-ingress inject terminus-language
  frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
  frameworks/bfl/config/launcher/templates/bfl_deploy.yaml
Labels: feat

#417 feat: update termipass v1.2.26
  apps/desktop/config/user/helm-charts/desktop/templates/desktop_deploy.yaml
  apps/files/config/user/helm-charts/files/templates/files_fe_deploy.yaml
  apps/settings/config/user/helm-charts/settings/templates/settings_deploy.yaml
  apps/vault/config/cluster/deploy/vault_server_deploy.yaml
  apps/vault/config/user/helm-charts/vault/templates/vault_deploy.yaml
  third-party/authelia/config/user/helm-charts/auth/templates/auth_deploy.yaml
Labels: feat

#418 fix: numeric username bug
  frameworks/system-server/config/user/helm-charts/systemserver/templates/systemserver_deploy.yaml
Labels: fix

#420 feat: update profile v2
  apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
Labels: feat

#421 feat: move headscale frontend to system-frontend
  apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
  third-party/headscale/config/user/helm-charts/headscale/templates/headscale_deploy.yaml
Labels: feat

#422 fix: increase http header max size
  apps/desktop/config/user/helm-charts/desktop/templates/desktop_deploy.yaml
  apps/files/config/user/helm-charts/files/templates/files_fe_deploy.yaml
  frameworks/bfl/config/launcher/templates/bfl_deploy.yaml
  third-party/authelia/config/cluster/deploy/auth_backend_deploy.yaml
Labels: fix

#425 feat: upgrade search3 to v0.0.12
  apps/search3/config/cluster/deploy/search3_server_deploy.yaml
Labels: feat

#426 fix: uploader cors bug
  apps/files/config/cluster/deploy/files_deploy.yaml
Labels: fix

#428 feat: supports playing media files in external storage
  apps/files/config/cluster/deploy/files_deploy.yaml
Labels: feat

#430 feat: set deploy/sts replicas to 0, when eviction occur on one node cluster
  frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
Labels: feat

#431 feat: disable settings upgrade & fix some bugs
  apps/settings/config/user/helm-charts/settings/templates/settings_deploy.yaml
Labels: feat

#427 ci: installer package refactor
  .github/workflows/build-redis.yaml
  .github/workflows/check.yaml
  .github/workflows/push-deps-to-s3.yml
  .github/workflows/release-daily.yaml
  .github/workflows/release.yaml
  build/installer/Makefile
  build/installer/change_ip.sh
  build/installer/common.sh
  build/installer/downloadInstaller.sh
  build/installer/install.sh
  build/installer/install_cmd.sh
  build/installer/install_macos.sh
  build/installer/publicAddnode.sh
  build/installer/publicInstaller.latest
  build/installer/publicInstaller.sh
  build/installer/publicRestoreInstaller.sh
  build/installer/uninstall_cmd.sh
  build/installer/uninstall_macos.sh
  build/manifest/components
  build/manifest/dependencies.amd64
  build/manifest/pkgs
  scripts/build-full.sh
  scripts/build-manifest.sh
  scripts/build-redis.sh
  scripts/build.sh
  scripts/deps-manifest.sh
  scripts/download-deps.sh
  scripts/image-manifest.sh
  scripts/import-images.sh
  scripts/save-deps.sh
  scripts/upload-deps.sh
  scripts/upload-images.sh
Labels: ci

#432 fix: terminus-cli 0.1.16
  build/installer/install.sh
Labels: fix

#433 fix: helm upgrade retry bug
  .github/workflows/check.yaml
  build/installer/install_cmd.sh
  build/manifest/components
Labels: fix

#434 fix: terminus-cli 0.1.17
  build/installer/install.sh
Labels: fix

#435 feat: get terminus name in terminusd
  build/manifest/components
Labels: feat

#438 fix: crash when clearing segments
  apps/files/config/cluster/deploy/files_deploy.yaml
Labels: fix

#442 feat: delay sending write msg in 1s
  libs/fs-lib/config/cluster/deploy/fsnotify_deploy.yaml
  libs/fs-lib/config/user/helm-charts/fsnotify/templates/fsnotify_deploy.yaml
Labels: feat

#443 feat: knowledge v0.1.44
  apps/argo/config/user/helm-charts/argo/charts/argoworkflows/templates/server/server-deployment.yaml
  apps/download/config/user/helm-charts/download/templates/download_deploy.yaml
  apps/knowledge/config/user/helm-charts/knowledge/templates/knowledge_deployment.yaml
  apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
Labels: feat

#444 feat: change host ip
  build/manifest/components
Labels: feat

#446 fix: nvshare cuMemAlloc modified
  build/installer/deploy/device-plugin.yaml
  build/manifest/images
  scripts/upload-gpu-deps.sh
Labels: fix

#447 fix: envoy outbound suport websocket upgrade;system frontend configmap format
  apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
  frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
Labels: fix

#448 fix: update search i18n for desktop
  apps/desktop/config/user/helm-charts/desktop/templates/desktop_deploy.yaml
  apps/wizard/config/user/helm-charts/wizard/templates/wizard_deploy.yaml
Labels: fix

#449 fix: change ip log
  build/installer/change_ip.sh
  build/manifest/components
Labels: fix

#450 fix: cli 0.1.19
  build/installer/install.sh
Labels: fix

#452 feat: update wise to wise:v1.2.30 and use rsshub docker
  apps/download/config/user/helm-charts/download/templates/download_deploy.yaml
  apps/knowledge/config/user/helm-charts/knowledge/templates/knowledge_deployment.yaml
  apps/rss/config/cluster/deploy/rss_deploy.yaml
  apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
Labels: feat

#453 fix: fix controlhub restart pod 404
  apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
Labels: fix

#454 fix: cli 0.1.20
  build/installer/install.sh
Labels: fix

#456 fix: terminusd uninstall bug
  build/manifest/components
Labels: fix

#455 fix: reset password bug
  frameworks/bfl/config/launcher/templates/bfl_deploy.yaml
  third-party/authelia/config/cluster/deploy/auth_backend_deploy.yaml
Labels: fix

#457 fix: envoy set probes route to path;envoy timeout
  frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
Labels: fix

#458 fix: migrate the authelia storage to postgres
  scripts/download-deps.sh
  scripts/upload-deps.sh
  third-party/authelia/config/cluster/deploy/auth_backend_deploy.yaml
Labels: fix

#461 fix: eviction from kubelet
  frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
Labels: fix

#459 fix: release archive package
  .github/workflows/release-daily.yaml
  .github/workflows/release.yaml
Labels: fix

#460 fix: cli 0.1.21
  build/installer/common.sh
  build/installer/install.sh
  build/installer/install_cmd.sh
  build/installer/install_macos.sh
Labels: fix

#463 feat: support switching and turning off reverse proxy
  apps/settings/config/user/helm-charts/settings/templates/settings_deploy.yaml
  frameworks/bfl/config/launcher/templates/bfl_deploy.yaml
Labels: feat

#464 feat: update wise to v1.2.33
  apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
Labels: feat

#465 feat: update knowledge to v0.1.46
  apps/download/config/user/helm-charts/download/templates/download_deploy.yaml
  apps/knowledge/config/user/helm-charts/knowledge/templates/knowledge_deployment.yaml
Labels: feat

#468 fix: jfsnotify proxy nil pointer bug
  libs/fs-lib/config/cluster/deploy/fsnotify_deploy.yaml
  libs/fs-lib/config/user/helm-charts/fsnotify/templates/fsnotify_deploy.yaml
Labels: fix

#467 fix: fix dashboard cluster source panel
  apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
Labels: fix

#466 fix: copy back install.sh after version string is injected
  .github/workflows/release-daily.yaml
  .github/workflows/release.yaml
Labels: fix

#469 fix: wrong path of install.sh
  .github/workflows/release-daily.yaml
  .github/workflows/release.yaml
Labels: fix

#470 fix: nvshare lib revert
  build/installer/deploy/device-plugin.yaml
Labels: fix

#471 fix: update dashboard i18n
  apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
Labels: fix

#473 fix: update images tag
  build/manifest/images
Labels: fix

#474 fix: update i18n
  apps/desktop/config/user/helm-charts/desktop/templates/desktop_deploy.yaml
Labels: fix

#475 feat: auth add internal auth-level
  frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
  third-party/authelia/config/cluster/deploy/auth_backend_deploy.yaml
Labels: feat

#476 feat: usb mount
  apps/files/config/cluster/deploy/files_deploy.yaml
  build/manifest/components
Labels: feat

#478 fix: update cli to 0.1.22
  build/installer/install.sh
Labels: fix

#480 fix: image download use mirror registry
  frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
Labels: fix

#481 fix: cli update to 0.1.24
  build/installer/install.sh
Labels: fix

#482 fix: terminusd v0.0.8
  build/manifest/components
Labels: fix

#484 feat: upgrade search3 to v0.0.15 and add space property word for process
  apps/search3/config/cluster/deploy/search3_server_deploy.yaml
Labels: feat

#483 fix: cli update to 0.1.25
  build/installer/install.sh
Labels: fix

#485 fix: ignore notification error when login
  apps/analytic/config/cluster/deploy/analytic_deploy.yaml
  apps/notifications/config/user/helm-charts/notification/templates/notification_deploy.yaml
  third-party/authelia/config/cluster/deploy/auth_backend_deploy.yaml
Labels: fix

#486 fix: cli update to 0.1.26
  build/installer/common.sh
  build/installer/install.sh
  build/installer/install_cmd.sh
Labels: fix

#487 fix: knowledge to v0.1.48
  apps/download/config/user/helm-charts/download/templates/download_deploy.yaml
  apps/knowledge/config/user/helm-charts/knowledge/templates/knowledge_deployment.yaml
Labels: fix

#488 fix: termipass v1.2.37 & profile v1.0.2 & settings v0.1.83
  apps/desktop/config/user/helm-charts/desktop/templates/desktop_deploy.yaml
  apps/files/config/user/helm-charts/files/templates/files_fe_deploy.yaml
  apps/settings/config/user/helm-charts/settings/templates/settings_deploy.yaml
  apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
  apps/vault/config/cluster/deploy/vault_server_deploy.yaml
  apps/vault/config/user/helm-charts/vault/templates/vault_deploy.yaml
  apps/wizard/config/user/helm-charts/wizard/templates/wizard_deploy.yaml
Labels: fix

#489 fix: update reverse proxy image version to v0.1.3
  build/manifest/images
  frameworks/bfl/config/launcher/templates/bfl_deploy.yaml
Labels: fix

#491 fix: update bfl version to v0.3.43
  frameworks/bfl/config/launcher/templates/bfl_deploy.yaml
Labels: fix

#493 feat: market v0.2.15
  apps/market/config/user/helm-charts/market/templates/market_deploy.yaml
  apps/market/config/user/helm-charts/market/values.yaml
  build/installer/install_cmd.sh
  build/installer/install_macos.sh
Labels: feat

#490 feat: upgrade beclab/drive to v0.0.5 and beclab/driveexecutor to v0.0.5
  apps/files/config/user/helm-charts/files/templates/files_fe_deploy.yaml
Labels: feat

#494 fix: restore kubeType
  build/installer/install.sh
  build/installer/install_cmd.sh
Labels: fix

#496 fix: image download progress;image pull retry strategy
  frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
Labels: fix

#495 feat: add terminusd info to terminus-info api
  apps/files/config/cluster/deploy/files_deploy.yaml
  build/installer/change_ip.sh
  build/installer/install_cmd.sh
  build/installer/wizard/config/settings/templates/terminus_cr.yaml
  build/manifest/components
  frameworks/bfl/config/launcher/templates/bfl_deploy.yaml
Labels: feat

#497 fix: sync ,crawler remove from argo
  apps/argo/config/user/helm-charts/argo/charts/argoworkflows/templates/server/server-deployment.yaml
  apps/knowledge/config/user/helm-charts/knowledge/templates/knowledge_deployment.yaml
Labels: fix

#498 feat: market v0.2.16 version
  apps/market/config/user/helm-charts/market/templates/market_deploy.yaml
Labels: feat

#499 fix: termipass v1.2.41
  apps/files/config/user/helm-charts/files/templates/files_fe_deploy.yaml
  apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
  apps/vault/config/cluster/deploy/vault_server_deploy.yaml
  apps/vault/config/user/helm-charts/vault/templates/vault_deploy.yaml
Labels: fix

#504 feat: release market v0.2.17
  apps/market/config/user/helm-charts/market/templates/market_deploy.yaml
Labels: feat

#503 fix: termipass v1.2.42
  apps/files/config/user/helm-charts/files/templates/files_fe_deploy.yaml
  apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
  apps/vault/config/cluster/deploy/vault_server_deploy.yaml
  apps/vault/config/user/helm-charts/vault/templates/vault_deploy.yaml
Labels: fix

#502 feat: argo workflow mutate image;more smooth pull progress calculate method
  frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
Labels: feat

#500 fix: cli update to 0.1.29
  build/installer/install.sh
Labels: fix

#506 fix: derp list optimization
  third-party/headscale/config/user/helm-charts/headscale/templates/headscale_deploy.yaml
Labels: fix

#507 feat: update vault, file, wise, market version
  apps/files/config/user/helm-charts/files/templates/files_fe_deploy.yaml
  apps/market/config/user/helm-charts/market/templates/market_deploy.yaml
  apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
  apps/vault/config/cluster/deploy/vault_server_deploy.yaml
  apps/vault/config/user/helm-charts/vault/templates/vault_deploy.yaml
Labels: feat

#508 feat: nvshare managed memory switching
  apps/settings/config/user/helm-charts/settings/templates/settings_deploy.yaml
  build/manifest/components
  frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
  frameworks/bfl/config/launcher/templates/bfl_deploy.yaml
Labels: feat

#509 feat: recommend backend to v0.0.16 (add rsshub cookie)
  apps/download/config/user/helm-charts/download/templates/download_deploy.yaml
  apps/knowledge/config/user/helm-charts/knowledge/templates/knowledge_deployment.yaml
  apps/rss/config/cluster/deploy/rss_deploy.yaml
Labels: feat

#510 fix: download config path
  apps/download/config/user/helm-charts/download/templates/download_deploy.yaml
Labels: fix

#511 fix: rsshub to v0.0.2
  apps/download/config/user/helm-charts/download/templates/download_deploy.yaml
  apps/rss/config/cluster/deploy/rss_deploy.yaml
Labels: fix

#512 fix: change ip bug when not installed
  build/manifest/components
Labels: fix

#513 ci: bump to 1.10.0
  .github/workflows/check.yaml
  .github/workflows/release-daily.yaml
  .github/workflows/release.yaml
  build/installer/install.sh
  build/installer/version.hint
Labels: ci

#514 fix: invalid containerd.sock after containerd restart
  frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
Labels: fix

#515 fix: download component
  build/installer/install_macos.sh
Labels: fix

#517 fix: update device-plugin.yaml
  build/installer/deploy/device-plugin.yaml
Labels: fix

#518 fix: macos kubeaddons dir not create
  build/installer/install.sh
Labels: fix

#519 feat: release market v0.2.20
  apps/market/config/user/helm-charts/market/templates/market_deploy.yaml
Labels: feat

#520 fix: ingress add terminus language for desktop
  frameworks/bfl/config/launcher/templates/bfl_deploy.yaml
Labels: fix
