Repository beclab/Olares, pull requests merged in 2024-08, with the labels that each got.

#280 fix: image update
  build/manifest/images
Labels: fix

#281 fix: velero resource
  build/installer/install_cmd.sh
  build/manifest/images
Labels: fix

#282 docs: fix bad links and fold tables in readme
  README.md
Labels: docs

#283 fix: kubectl path and k8s preload images path
  build/installer/install_cmd.sh
  build/installer/install_macos.sh
Labels: fix

#284 fix: update installer
  build/installer/install_cmd.sh
  build/installer/install_macos.sh
Labels: fix

#285 fix: velero resource adjustment
  build/installer/install_cmd.sh
Labels: fix

#286 feat: add support for nats
  apps/market/config/user/helm-charts/market/templates/market_deploy.yaml
  frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
  frameworks/bfl/config/launcher/templates/bfl_deploy.yaml
  frameworks/system-server/config/user/helm-charts/systemserver/templates/systemserver_deploy.yaml
  frameworks/tapr/config/cluster/crds/apr.bytetrade.io_middlewarerequests.yaml
  frameworks/tapr/config/cluster/deploy/middleware_deploy.yaml
  frameworks/tapr/config/cluster/deploy/nats_deployment.yaml
  frameworks/tapr/config/user/helm-charts/nats/.helmignore
  frameworks/tapr/config/user/helm-charts/nats/Chart.yaml
  frameworks/tapr/config/user/helm-charts/nats/templates/NOTES.txt
  frameworks/tapr/config/user/helm-charts/nats/templates/_helpers.tpl
  frameworks/tapr/config/user/helm-charts/nats/templates/deployment.yaml
  frameworks/tapr/config/user/helm-charts/nats/values.yaml
Labels: feat

#288 fix: oidc bug & authelia crash on start up
  apps/wizard/config/user/helm-charts/wizard/templates/wizard_deploy.yaml
  build/installer/install_cmd.sh
  third-party/authelia/config/cluster/deploy/auth_backend_deploy.yaml
  third-party/authelia/config/user/helm-charts/auth/templates/auth_deploy.yaml
Labels: fix

#287 fix: change nat export to arrary;all user app list api
  frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
  frameworks/bfl/config/launcher/templates/bfl_deploy.yaml
  frameworks/tapr/config/cluster/crds/apr.bytetrade.io_middlewarerequests.yaml
  frameworks/tapr/config/cluster/deploy/middleware_deploy.yaml
Labels: fix

#289 feat: support playing videos in Sync
  apps/files/config/cluster/deploy/files_deploy.yaml
  third-party/seahub/config/cluster/deploy/seafile_deploy.yaml
Labels: feat

#291 fix: download image obey image pullpolicy;fire an error when containerd is down
  build/installer/deploy/patch-globalrole-workspace-manager.yaml
  frameworks/app-service/config/cluster/crds/app.bytetrade.io_imagemanagers.yaml
  frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
Labels: fix

#290 feat: files watch /Home/Documents for search3
  apps/files/config/cluster/deploy/files_deploy.yaml
  libs/fs-lib/config/cluster/deploy/fsnotify_deploy.yaml
Labels: feat

#293 fix: change ip bug on wsl
  build/installer/change_ip.sh
Labels: fix

#292 fix: change ip bug on wsl
  build/installer/change_ip.sh
Labels: fix

#295 fix: add kubesphere redis to the dependencies of authelia
  third-party/authelia/config/cluster/deploy/auth_backend_deploy.yaml
Labels: fix

#296 fix: jfsnotify os-system bug
  libs/fs-lib/config/cluster/deploy/fsnotify_deploy.yaml
Labels: fix

#299 fix: add cuda lib fixing to k3s service as a pre-task
  build/installer/install_cmd.sh
Labels: fix

#305 fix: download bug
  apps/download/config/user/helm-charts/download/templates/download_deploy.yaml
  apps/knowledge/config/user/helm-charts/knowledge/templates/knowledge_deployment.yaml
  apps/wise/config/user/helm-charts/wise/templates/wise_deployment.yaml
Labels: fix

#303 fix: update controlhub and dashboard disk unit
  apps/system-apps/config/user/helm-charts/monitoring/templates/monitoring_deploy.yaml
  apps/system-apps/config/user/helm-charts/system/templates/admin_console_deploy.yaml
Labels: fix

#302 fix: update controlhub and dashboard disk unit
  apps/system-apps/config/user/helm-charts/monitoring/templates/monitoring_deploy.yaml
  apps/system-apps/config/user/helm-charts/system/templates/admin_console_deploy.yaml
Labels: fix

#301 fix: raspberry pi os validation
  build/installer/install_cmd.sh
Labels: fix

#309 feat: termipass v1.2.19
  apps/files/config/user/helm-charts/files/templates/files_fe_deploy.yaml
  apps/vault/config/cluster/deploy/vault_server_deploy.yaml
  apps/vault/config/user/helm-charts/vault/templates/vault_deploy.yaml
Labels: feat

#308 fix: update market app details ui
  apps/market/config/user/helm-charts/market/templates/market_deploy.yaml
Labels: fix

#307 fix: update market app details ui
  apps/market/config/user/helm-charts/market/templates/market_deploy.yaml
Labels: fix

#306 feat: search upgrade for desktop
  apps/desktop/config/user/helm-charts/desktop/templates/desktop_deploy.yaml
Labels: feat

#313 feat: downloading image files
  .github/workflows/push-to-s3.yaml
  .github/workflows/release-daily.yaml
  .github/workflows/release-weekly.yaml
  .github/workflows/release.yaml
  apps/files/config/cluster/deploy/files_deploy.yaml
  build/installer/deploy/device-plugin.yaml
  build/installer/deploy/scheduler.yaml
  build/installer/install_cmd.sh
  build/installer/install_macos.sh
  build/manifest/images
  scripts/build.sh
Labels: feat

#300 fix: add cuda lib fixing to k3s service as pre-task
  build/installer/install_cmd.sh
  third-party/authelia/config/cluster/deploy/auth_backend_deploy.yaml
Labels: fix

#310 fix: audio-only media not playing
  apps/files/config/cluster/deploy/files_deploy.yaml
Labels: fix

#312 fix: delete unmanaged-pvc;change imagemangers update retry strategy
  apps/files/config/cluster/deploy/files_deploy.yaml
  frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
  frameworks/tapr/config/cluster/deploy/nats_deployment.yaml
Labels: fix

#314 feat: Search Upgrade
  apps/desktop/config/user/helm-charts/desktop/templates/desktop_deploy.yaml
  apps/wise/config/user/helm-charts/wise/templates/wise_deployment.yaml
Labels: feat

#315 fix: set fs type when system app installing
  build/installer/install_cmd.sh
Labels: fix

#316 fix: clear the anonymous session
  apps/files/config/cluster/deploy/files_deploy.yaml
  build/installer/deploy/device-plugin.yaml
  third-party/authelia/config/cluster/deploy/auth_backend_deploy.yaml
Labels: fix

#317 feat: uninstall using terminus-cli
  build/installer/install.sh
  build/installer/install_cmd.sh
  build/installer/install_macos.sh
  build/installer/uninstall_cmd.sh
  build/installer/uninstall_macos.sh
Labels: feat

#318 fix: updates synchronize
  apps/files/config/cluster/deploy/files_deploy.yaml
  build/installer/deploy/device-plugin.yaml
  build/installer/install_cmd.sh
  third-party/authelia/config/cluster/deploy/auth_backend_deploy.yaml
Labels: fix

#319 fix: update textSearch
  apps/desktop/config/user/helm-charts/desktop/templates/desktop_deploy.yaml
Labels: fix

#321 feat: update knowledge to v0.1.42
  apps/wise/config/user/helm-charts/wise/templates/wise_deployment.yaml
Labels: feat

#320 feat: update knowledge to v0.1.42
  apps/wise/config/user/helm-charts/wise/templates/wise_deployment.yaml
Labels: feat

#322 feat: knowledge version updated to v0.1.42
  apps/knowledge/config/user/helm-charts/knowledge/templates/knowledge_deployment.yaml
Labels: feat

#325 fix: optimized controlhub and dashboard
  apps/system-apps/config/user/helm-charts/monitoring/templates/monitoring_deploy.yaml
  apps/system-apps/config/user/helm-charts/system/templates/admin_console_deploy.yaml
  frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
Labels: fix

#326 fix: youtube download
  apps/download/config/user/helm-charts/download/templates/download_deploy.yaml
  apps/knowledge/config/user/helm-charts/knowledge/templates/knowledge_deployment.yaml
Labels: fix

#324 feat: update installer
  .github/workflows/push-to-s3.yaml
  .github/workflows/release.yaml
  build/installer/install.sh
  build/installer/install_cmd.sh
  build/installer/uninstall_cmd.sh
  build/installer/uninstall_macos.sh
  build/manifest/images
Labels: feat

#328 fix: remove install-wizard
  build/installer/install.sh
  build/installer/publicInstaller.latest
  build/installer/publicInstaller.sh
Labels: fix

#330 fix: fix controlhub multiple users permissions
  apps/system-apps/config/cluster/deploy/ks_server_deploy.yaml
  apps/system-apps/config/user/helm-charts/system/templates/admin_console_deploy.yaml
Labels: fix

#329 fix: fixed some bug for text search
  apps/desktop/config/user/helm-charts/desktop/templates/desktop_deploy.yaml
Labels: fix

#331 feat: add recommend model
  apps/argo/config/user/helm-charts/argo/charts/argoworkflows/templates/server/server-deployment.yaml
Labels: feat

#332 fix: change the path of installed lock file
  build/installer/install.sh
  build/installer/publicInstaller.latest
  build/installer/uninstall_cmd.sh
Labels: fix

#333 fix: change the path of installed lock file
  build/installer/install.sh
  build/installer/publicInstaller.latest
  build/installer/uninstall_cmd.sh
Labels: fix

#335 fix: remove unrelated directory operations
  build/installer/install_cmd.sh
Labels: fix

#334 fix: nvidia-ctk use external containerd
  build/installer/install_cmd.sh
Labels: fix

#336 fix: fix controlhub some bugs
  apps/system-apps/config/user/helm-charts/system/templates/admin_console_deploy.yaml
Labels: fix

#337 feat: system-frontend merge dashboard,controlhub;set auth default policy follow system auth policy
  apps/system-apps/config/user/helm-charts/monitoring/templates/monitoring_deploy.yaml
  apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
  apps/system-apps/config/user/helm-charts/system/.helmignore
  apps/system-apps/config/user/helm-charts/system/Chart.yaml
  apps/system-apps/config/user/helm-charts/system/templates/NOTES.txt
  apps/system-apps/config/user/helm-charts/system/templates/_helpers.tpl
  apps/system-apps/config/user/helm-charts/system/templates/admin_console_deploy.yaml
  apps/system-apps/config/user/helm-charts/system/values.yaml
  build/installer/deploy/patch-globalrole-workspace-manager.yaml
  frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
  third-party/authelia/config/cluster/deploy/auth_backend_deploy.yaml
Labels: feat

#338 feat: download version updated to v0.0.4
  apps/download/config/user/helm-charts/download/templates/download_deploy.yaml
  apps/knowledge/config/user/helm-charts/knowledge/templates/knowledge_deployment.yaml
Labels: feat

#339 fix: add apiextensions permission for second user
  build/installer/deploy/patch-globalrole-workspace-manager.yaml
Labels: fix

#341 fix: .installed path
  build/installer/install_cmd.sh
Labels: fix

#343 fix: can not connect to containerd in k3s
  frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
Labels: fix

#342 feat: webhook for crd imagemanager
  frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
Labels: feat

#344 fix: nats imagePullPolicy
  frameworks/tapr/config/cluster/deploy/nats_deployment.yaml
Labels: fix

#345 feat: update edit and view YAML type
  apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
Labels: feat

#346 feat: force all pods running as user 1000
  apps/desktop/config/user/helm-charts/desktop/templates/desktop_deploy.yaml
  apps/download/config/user/helm-charts/download/templates/download_deploy.yaml
  apps/files/config/cluster/deploy/files_deploy.yaml
  apps/files/config/user/helm-charts/files/templates/files_fe_deploy.yaml
  apps/knowledge/config/user/helm-charts/knowledge/templates/knowledge_deployment.yaml
  apps/nitro/config/cluster/deploy/nitro_deploy.yaml
  apps/profile/config/user/helm-charts/profile/templates/profile_deployment.yaml
  build/installer/install_cmd.sh
  frameworks/GPU/config/gpu/templates/client-update.yaml
  frameworks/GPU/config/gpu/templates/container-runtime.yaml
  frameworks/GPU/config/gpu/templates/device-plugin.yaml
  frameworks/GPU/config/gpu/templates/orion-server.yaml
  frameworks/bfl/config/launcher/templates/bfl_deploy.yaml
  frameworks/tapr/config/user/helm-charts/tapr/templates/tapr_deploy.yaml
  third-party/headscale/config/user/helm-charts/headscale/templates/headscale_deploy.yaml
Labels: feat

#347 feat: uploader change
  apps/files/config/cluster/deploy/files_deploy.yaml
  apps/files/config/user/helm-charts/files/templates/files_fe_deploy.yaml
Labels: feat

#349 fix: retry for built-in app installation
  build/installer/install_cmd.sh
Labels: fix

#351 fix: update controlhub toolbar actions style
  apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
Labels: fix

#352 fix: fix english chinese search together
  apps/search3/config/cluster/deploy/search3_server_deploy.yaml
Labels: fix

#353 fix: fix google drive list, refactor google drive operation
  apps/files/config/user/helm-charts/files/templates/files_fe_deploy.yaml
Labels: fix

#354 fix: update google drive
  apps/files/config/user/helm-charts/files/templates/files_fe_deploy.yaml
  apps/vault/config/cluster/deploy/vault_server_deploy.yaml
  apps/vault/config/user/helm-charts/vault/templates/vault_deploy.yaml
Labels: fix

#355 fix: update deps manifest
  .github/workflows/push-deps-to-s3.yml
  build/manifest/dependencies.amd64
  build/manifest/dependencies.arm64
  scripts/build-full.sh
  scripts/download-deps.sh
Labels: fix

#356 fix: fix controlhub Terminal and Log permissions
  apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
Labels: fix

#357 fix: use compiled redis
  build/installer/install_cmd.sh
Labels: fix

#358 fix: remove sync, crawler from argo
  apps/argo/config/user/helm-charts/argo/charts/argoworkflows/templates/server/server-deployment.yaml
  apps/knowledge/config/user/helm-charts/knowledge/templates/knowledge_deployment.yaml
Labels: fix

#362 fix: update installer and k3s and containerd separation
  build/installer/install_cmd.sh
Labels: fix

#361 fix: create rss data directory automatically
  apps/knowledge/config/user/helm-charts/knowledge/templates/knowledge_deployment.yaml
Labels: fix

#364 feat: all folders watched in Drive, with special folder also parsed content
  apps/files/config/cluster/deploy/files_deploy.yaml
Labels: feat

#365 feat: update settings version to v0.1.75
  apps/settings/config/user/helm-charts/settings/templates/settings_deploy.yaml
Labels: feat

#367 fix: build images manifest
  scripts/build.sh
Labels: fix

#368 fix: format images.mf
  build/manifest/images
Labels: fix

#369 fix: md5
  build/installer/install_macos.sh
Labels: fix

#370 fix: uninstall for .prepared
  build/installer/uninstall_cmd.sh
Labels: fix

#371 fix: numeric user name
  build/installer/wizard/config/settings/templates/globalrole-binding.yaml
  build/installer/wizard/config/settings/templates/system_namespace.yaml
  build/installer/wizard/config/settings/templates/user-namespace.yaml
  build/installer/wizard/config/settings/templates/user-namespacerole-binding.yaml
  build/installer/wizard/config/settings/templates/user-system-ns.yaml
  build/installer/wizard/config/settings/templates/user-systemrole-binding.yaml
  build/installer/wizard/config/settings/templates/workspacerole-binding.yaml
Labels: fix

#372 fix: update for macos
  build/installer/install_macos.sh
Labels: fix

#374 fix: sync memory
  apps/argo/config/user/helm-charts/argo/charts/argoworkflows/templates/server/server-deployment.yaml
  apps/knowledge/config/user/helm-charts/knowledge/templates/knowledge_deployment.yaml
Labels: fix

#376 fix: remove cluster for prepared
  build/installer/uninstall_cmd.sh
Labels: fix

#378 ci: build redis
  .github/workflows/build-redis.yaml
  scripts/build-redis.sh
Labels: ci

#377 fix: add proxmox support
  build/installer/install.sh
  build/installer/install_cmd.sh
  build/installer/publicInstaller.latest
  build/installer/publicInstaller.sh
Labels: fix

#379 fix: Improve the validation of the pve
  build/installer/install_cmd.sh
Labels: fix

#380 feat: add allocatable pod check for user create;config system api
  frameworks/bfl/config/launcher/templates/bfl_deploy.yaml
Labels: feat

#381 fix: sync memory
  apps/argo/config/user/helm-charts/argo/charts/argoworkflows/templates/server/server-deployment.yaml
Labels: fix

#382 fix: jfsnotify daemon crash
  libs/fs-lib/config/cluster/deploy/fsnotify_daemon.yaml
Labels: fix

#384 feat: move profile to system frontend deployment
  apps/profile/README.md
  apps/profile/config/user/helm-charts/profile/.helmignore
  apps/profile/config/user/helm-charts/profile/Chart.yaml
  apps/profile/config/user/helm-charts/profile/templates/NOTES.txt
  apps/profile/config/user/helm-charts/profile/templates/_helpers.tpl
  apps/profile/config/user/helm-charts/profile/templates/profile_deployment.yaml
  apps/profile/config/user/helm-charts/profile/values.yaml
  apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
  build/installer/install_cmd.sh
  build/installer/install_macos.sh
Labels: feat

#385 fix: uninstall script
  build/installer/uninstall_cmd.sh
Labels: fix

#383 docs: fix Discord link
  README.md
Labels: docs

#387 feat: Add Sync for Search and spell checker
  apps/desktop/config/user/helm-charts/desktop/templates/desktop_deploy.yaml
Labels: feat

#388 fix: bump juicefs-ext to 11.1.1
  build/installer/install_cmd.sh
  build/installer/publicAddnode.sh
  build/installer/upgrade_cmd.sh
  build/manifest/dependencies.amd64
  build/manifest/dependencies.arm64
Labels: fix

#389 fix: settings server save cookie error
  apps/settings/config/user/helm-charts/settings/templates/settings_deploy.yaml
Labels: fix

#391 fix: update search to v0.0.11 which fix detect short language error
  apps/search3/config/cluster/deploy/search3_server_deploy.yaml
Labels: fix

#392 feat: move wise frontend to system frontend
  apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
  apps/wise/README.md
  apps/wise/config/user/helm-charts/wise/.helmignore
  apps/wise/config/user/helm-charts/wise/Chart.yaml
  apps/wise/config/user/helm-charts/wise/templates/NOTES.txt
  apps/wise/config/user/helm-charts/wise/templates/_helpers.tpl
  apps/wise/config/user/helm-charts/wise/templates/wise_deployment.yaml
  apps/wise/config/user/helm-charts/wise/values.yaml
Labels: feat

#394 fix: Listen message for Iframe
  apps/desktop/config/user/helm-charts/desktop/templates/desktop_deploy.yaml
Labels: fix

#396 fix: change buffer location to fix a new found copy bug after running as user 1000
  apps/files/config/cluster/deploy/files_deploy.yaml
Labels: fix

#397 fix: ignore localhost ip as node ip
  frameworks/bfl/config/launcher/templates/bfl_deploy.yaml
Labels: fix

#398 fix: validate host ip on macos
  build/installer/install_macos.sh
Labels: fix

#399 fix: validate host ip on macos
  build/installer/install_macos.sh
Labels: fix

#400 feat: add shared lib path
  apps/files/config/cluster/deploy/files_deploy.yaml
  build/installer/install_cmd.sh
  frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
Labels: feat

#402 feat: wise to v0.1.43
  apps/argo/config/user/helm-charts/argo/charts/argoworkflows/templates/server/server-deployment.yaml
  apps/knowledge/config/user/helm-charts/knowledge/templates/knowledge_deployment.yaml
  apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
Labels: feat

#401 feat: inject window push state script
  apps/files/config/user/helm-charts/files/templates/files_fe_deploy.yaml
  apps/market/config/user/helm-charts/market/templates/market_deploy.yaml
  apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
  apps/vault/config/cluster/deploy/vault_server_deploy.yaml
  apps/vault/config/user/helm-charts/vault/templates/vault_deploy.yaml
  frameworks/app-service/config/cluster/crds/app.bytetrade.io_applications.yaml
  frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
  frameworks/bfl/config/launcher/templates/bfl_deploy.yaml
Labels: feat

#403 fix: add registry-mirrors
  build/installer/install_cmd.sh
Labels: fix

#404 feat: seahub authenticate with X-Bfl-User (no need login/token/session again)
  third-party/seahub/config/cluster/deploy/seafile_deploy.yaml
Labels: feat

#405 fix: modify the prompt
  build/installer/install_cmd.sh
  build/installer/install_macos.sh
Labels: fix
