Repository beclab/Olares, pull requests merged in 2024-05, with the labels that each got.

#61 ci: add validating step to workflow and git-hook to the code committing
  .githooks/commit-msg
  .githooks/git-hooks-config.sh
  .github/workflows/check.yaml
  .github/workflows/release-daily.yaml
Labels: ci

#67 docs: fix banner image
  README.md
  images/banner2.jpg
Labels: docs

#68 docs: fix image display issue
  README.md
Labels: docs

#69 fix: orion gpu runtime broken on Ubuntu 22.04
  build/installer/uninstall_cmd.sh
  frameworks/GPU/config/gpu/templates/container-runtime.yaml
  frameworks/bfl/config/launcher/templates/bfl_deploy.yaml
Labels: fix

#63 fix: system upgrading will be broken in multi-user mode
  build/installer/upgrade_cmd.sh
Labels: fix

#70 feat: add check for the existence of local dependency files
  build/installer/install_cmd.sh
  build/manifest/images
Labels: feat

#72 fix: unable to update changed local IP when Cloudflare tunnel enabled
  frameworks/bfl/config/launcher/templates/bfl_deploy.yaml
Labels: fix

#71 fix: gpu limit inject override resource requests
  frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
Labels: fix

#75 fix: add quatation mark to BFL_NAME in files and fix a dify auto login bug with old cookie
  apps/files/config/user/helm-charts/files/templates/files_deploy.yaml
  apps/nitro/config/cluster/deploy/dify_deploy.yaml
Labels: fix

#74 fix: restart some pods to make sure the system recovery
  build/installer/change_ip.sh
Labels: fix

#77 feat: package and push dependency files for terminus installation to S3
  build/manifest/dependencies
  scripts/deps-manifest.sh
  scripts/upload-deps.sh
Labels: feat

#78 feat: add build artifact for pushing dependency files to S3
  .github/workflows/push-deps-to-s3.yml
Labels: feat

#79 fix: files can't get default dataset bug
  apps/files/config/user/helm-charts/files/templates/files_deploy.yaml
Labels: fix

#81 fix: support offline installation packages for k8s
  build/manifest/dependencies
  scripts/build-full.sh
  scripts/deps-manifest.sh
  scripts/download-deps.sh
  scripts/save-deps.sh
  scripts/upload-deps.sh
Labels: fix

#82 fix: copy pre-installation dependency files
  build/installer/install_cmd.sh
  build/manifest/dependencies
Labels: fix

#83 fix: curl download failure, as well as other errors
  build/installer/install_cmd.sh
  build/manifest/dependencies
  scripts/build-full.sh
  scripts/deps-manifest.sh
  scripts/download-deps.sh
  scripts/upload-deps.sh
Labels: fix

#86 feat: update vault & files version to v0.4.64
  apps/files/config/user/helm-charts/files/templates/files_deploy.yaml
  apps/vault/config/cluster/deploy/vault_server_deploy.yaml
  apps/vault/config/user/helm-charts/vault/templates/vault_deploy.yaml
Labels: feat

#85 feat: update settings version to v0.1.65
  apps/settings/config/user/helm-charts/settings/templates/settings_deploy.yaml
Labels: feat

#84 fix: optimize installation for k8s environment
  build/installer/install_cmd.sh
  build/manifest/dependencies
  build/manifest/images
Labels: fix

#87 fix: lower the minimum upgradable version
  build/installer/change_ip.sh
  build/installer/version.hint
  frameworks/bfl/config/launcher/templates/bfl_deploy.yaml
Labels: fix

#89 feat: add font subset
  apps/knowledge/config/user/helm-charts/knowledge/templates/knowledge_deployment.yaml
  apps/settings/config/user/helm-charts/settings/templates/settings_deploy.yaml
  apps/wise/config/user/helm-charts/wise/templates/wise_deployment.yaml
Labels: feat

#90 fix: pull velero image failed
  build/installer/install_cmd.sh
  build/manifest/images
Labels: fix

#91 fix: controhub and dashboard icon woff update
  apps/system-apps/config/user/helm-charts/monitoring/templates/monitoring_deploy.yaml
  apps/system-apps/config/user/helm-charts/system/templates/admin_console_deploy.yaml
Labels: fix

#94 feat: add orion gpu container-runtime pod running status check
  build/installer/install_cmd.sh
Labels: feat

#92 feat: manually chunk in files and context down to 1024 in dify
  apps/files/config/user/helm-charts/files/templates/files_deploy.yaml
  apps/nitro/config/cluster/deploy/dify_deploy.yaml
Labels: feat

#96 feat: update readme with multiple sections, diagrams, tables
  README.md
Labels: feat

#97 fix: fix table formatting in readme
  README.md
Labels: fix

#98 fix: fix typos, table formatting issues
  README.md
Labels: fix

#95 feat: ubuntu gpu dependency file collection and push to S3
  .github/workflows/push-gpudeps-to-s3.yml
  build/installer/install_cmd.sh
  scripts/upload-gpu-deps.sh
Labels: feat

#100 fix: optimize feature comparison table
  README.md
Labels: fix

#102 docs: Add <br> behind juciefs
  README.md
Labels: docs
