Repository beclab/Olares, pull requests merged in 2024-11, with the labels that each got.

#593 feat: uploader retransfers files when uploading folder or multi-files
  apps/files/config/cluster/deploy/files_deploy.yaml
Labels: feat

#596 fix: update CLI version to 0.1.39
  build/installer/install.sh
Labels: fix

#595 fix: wrong base dir for install command
  build/manifest/components
Labels: fix

#597 fix: fix controlHub and dashboard ui
  apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
Labels: fix

#598 feat: custom derpmap url
  third-party/headscale/config/user/helm-charts/headscale/templates/headscale_deploy.yaml
Labels: feat

#600 feat: update CLI version to 0.1.40
  build/installer/install.sh
Labels: feat

#599 fix: doing the changing ip command via terminus-cli
  build/manifest/components
Labels: fix

#604 feat: add global envs for multiple components
  apps/files/config/user/helm-charts/files/templates/files_fe_deploy.yaml
  apps/settings/config/user/helm-charts/settings/templates/settings_deploy.yaml
  apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
  apps/vault/config/cluster/deploy/vault_server_deploy.yaml
  apps/vault/config/user/helm-charts/vault/templates/vault_deploy.yaml
  build/installer/install.sh
  frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
  frameworks/backup-server/config/cluster/deploy/backup_server.yaml
  frameworks/osnode-init/config/cluster/deploy/nodeinit_daemonset.yaml
  third-party/headscale/config/user/helm-charts/headscale/templates/headscale_deploy.yaml
Labels: feat

#601 ci: build Ubuntu2204.appx
  .github/workflows/build-ubuntu2204.yaml
  scripts/build-ubuntu2204.sh
Labels: ci

#603 feat: update market/settings new version support Olares
  apps/desktop/config/user/helm-charts/desktop/templates/desktop_deploy.yaml
  apps/market/config/user/helm-charts/market/templates/market_deploy.yaml
  apps/wizard/config/user/helm-charts/wizard/templates/wizard_deploy.yaml
Labels: feat

#605 fix: update version
  apps/wizard/config/user/helm-charts/wizard/templates/wizard_deploy.yaml
Labels: fix

#607 feat: allow scheme in frp server enpoint
  build/manifest/images
  frameworks/bfl/config/launcher/templates/bfl_deploy.yaml
Labels: feat

#608 fix: use helm templating instead of sed replace
  build/installer/install.sh
  build/installer/wizard/config/settings/templates/terminus_cr.yaml
Labels: fix

#609 feat: release market v0.2.25
  apps/market/config/user/helm-charts/market/templates/market_deploy.yaml
Labels: feat

#610 feat: change terminusd binary name
  build/installer/install.sh
  build/manifest/components
Labels: feat

#611 feat: add install script in Windows powershell
  .github/workflows/release.yaml
  build/installer/install.ps1
  build/installer/install.sh
  scripts/build.sh
Labels: feat

#616 docs: update tech stack CDN link for readme
  README.md
  README_CN.md
Labels: docs

#614 fix: update beclab/login:v0.1.31
  apps/desktop/config/user/helm-charts/desktop/templates/desktop_deploy.yaml
  apps/notifications/config/user/helm-charts/notification/templates/notification_deploy.yaml
  third-party/authelia/config/user/helm-charts/auth/templates/auth_deploy.yaml
Labels: fix

#617 feat: change brand-related paths to Olares
  apps/analytic/config/cluster/deploy/analytic_deploy.yaml
  apps/files/config/cluster/deploy/files_deploy.yaml
  apps/nitro/config/cluster/deploy/nitro_deploy.yaml
  apps/vault/config/cluster/deploy/vault_server_deploy.yaml
  build/installer/Makefile
  build/installer/change_ip.sh
  build/installer/install.ps1
  build/installer/install.sh
  build/installer/publicAddnode.sh
  build/installer/publicRestoreInstaller.sh
  build/installer/refresh_sts.sh
  build/installer/upgrade_cmd.sh
  build/manifest/components
  build/manifest/images.node.mf
  frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
  frameworks/backup-server/config/cluster/deploy/backup_server.yaml
  frameworks/bfl/config/launcher/templates/bfl_deploy.yaml
  frameworks/osnode-init/config/cluster/deploy/nodeinit_daemonset.yaml
  frameworks/tapr/config/cluster/deploy/citus_deployment.yaml
  frameworks/tapr/config/cluster/deploy/fakes3_deployment.yaml
  frameworks/tapr/config/cluster/deploy/middleware_deploy.yaml
  frameworks/tapr/config/cluster/deploy/nats_deployment.yaml
  frameworks/tapr/config/cluster/deploy/redixcluster_deploy.yaml
  third-party/authelia/config/cluster/deploy/auth_backend_deploy.yaml
  third-party/seahub/config/cluster/deploy/seafile_deploy.yaml
Labels: feat

#618 fix: update login to v0.1.32
  third-party/authelia/config/user/helm-charts/auth/templates/auth_deploy.yaml
Labels: fix

#620 docs: add intro video in readme
  README.md
  README_CN.md
Labels: docs

#619 fix: support download cdn url
  build/installer/install.ps1
  build/installer/install.sh
  scripts/build-manifest.sh
Labels: fix

#621 docs: update license title to Olares
  LICENSE.md
Labels: docs

#622 fix: add startup probe for ks-controller-manager
  build/installer/install.sh
Labels: fix

#624 fix: revert the state olares-running to terminus-running
  build/manifest/components
Labels: fix

#627 fix: check ip changing result
  build/manifest/components
Labels: fix

#628 fix: fixed ui bugs for desktop and login
  apps/desktop/config/user/helm-charts/desktop/templates/desktop_deploy.yaml
  third-party/authelia/config/user/helm-charts/auth/templates/auth_deploy.yaml
Labels: fix

#629 feat: wise crawler add headless browser
  apps/knowledge/config/user/helm-charts/knowledge/templates/knowledge_deployment.yaml
Labels: feat

#631 feat: add API to retrieve the default reverse proxy config
  frameworks/bfl/config/launcher/templates/bfl_deploy.yaml
Labels: feat

#630 feat: add frp info to status api
  build/manifest/components
Labels: feat

#633 fix: update CLI version to 0.1.55
  build/installer/install.sh
Labels: fix

#632 feat: release vault and settings new version
  apps/files/config/user/helm-charts/files/templates/files_fe_deploy.yaml
  apps/settings/config/user/helm-charts/settings/templates/settings_deploy.yaml
  apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
  apps/vault/config/cluster/deploy/vault_server_deploy.yaml
  apps/vault/config/user/helm-charts/vault/templates/vault_deploy.yaml
Labels: feat

#634 fix: installing and ip changing state bug
  build/manifest/components
Labels: fix

#635 fix: theme switch
  apps/market/config/user/helm-charts/market/templates/market_deploy.yaml
  apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
Labels: fix

#637 fix: theme switch 1.10
  apps/market/config/user/helm-charts/market/templates/market_deploy.yaml
  apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
Labels: fix

#638 fix: add rootPath for helm values
  build/installer/install.sh
  frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
Labels: fix

#640 fix: update sync and download
  apps/download/config/user/helm-charts/download/templates/download_deploy.yaml
  apps/knowledge/config/user/helm-charts/knowledge/templates/knowledge_deployment.yaml
Labels: fix

#642 docs: add a rebranding note in readme to clear confusion
  README.md
Labels: docs

#643 feat: update backend to v0.0.23
  apps/knowledge/config/user/helm-charts/knowledge/templates/knowledge_deployment.yaml
Labels: feat

#646 fix: yt-dlp remove oauth
  apps/download/config/user/helm-charts/download/templates/download_deploy.yaml
Labels: fix

#645 feat: add custom cpu/memory threshold for suspend app
  frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
Labels: feat

#648 feat: image-service add support for http mirror
  frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
Labels: feat

#649 fix: update v1.2.62 for larePass
  apps/files/config/user/helm-charts/files/templates/files_fe_deploy.yaml
  apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
  apps/vault/config/cluster/deploy/vault_server_deploy.yaml
  apps/vault/config/user/helm-charts/vault/templates/vault_deploy.yaml
Labels: fix

#650 fix: fix controlHub terminal link
  apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
Labels: fix

#651 fix: make systemd always restart redis
  build/installer/install.sh
Labels: fix

#652 feat: ip-changing can be resumed if reboot device
  build/manifest/components
Labels: feat

#658 fix: add truncate option for different type of logs
  build/installer/install.ps1
  build/installer/install.sh
Labels: fix

#657 fix: change ip bug if os not installed
  build/manifest/components
Labels: fix

#660 fix: preload font 1.10
  apps/market/config/user/helm-charts/market/templates/market_deploy.yaml
  apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
Labels: fix

#661 fix: add an ip service provider
  frameworks/bfl/config/launcher/templates/bfl_deploy.yaml
Labels: fix

#664 fix: closed channel causes panic
  frameworks/bfl/config/launcher/templates/bfl_deploy.yaml
Labels: fix

#665 feat: add support for install.sh to build local release of Olares
  build/installer/install.sh
Labels: feat

#666 fix: nvshare switch not update deployment with gpu
  frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
Labels: fix

#667 ci: upload release package to cos
  .github/workflows/check.yaml
  .github/workflows/push-deps-to-s3.yml
  .github/workflows/push-gpudeps-to-s3.yml
  .github/workflows/push-to-s3.yaml
  .github/workflows/release-daily.yaml
  .github/workflows/release.yaml
  .github/workflows/upload-full.yaml
  scripts/upload-deps.sh
  scripts/upload-gpu-deps.sh
  scripts/upload-images.sh
Labels: ci

#668 fix: debian add-apt-repository
  build/installer/install.ps1
  build/installer/install.sh
Labels: fix

#670 fix: preload font
  apps/market/config/user/helm-charts/market/templates/market_deploy.yaml
  apps/settings/config/user/helm-charts/settings/templates/settings_deploy.yaml
  apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
Labels: fix

#669 fix: preload font
  apps/market/config/user/helm-charts/market/templates/market_deploy.yaml
  apps/settings/config/user/helm-charts/settings/templates/settings_deploy.yaml
  apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
Labels: fix

#672 fix: harmful chown on raspberry pi
  build/manifest/components
Labels: fix

#674 fix: update preview img for files
  apps/files/config/user/helm-charts/files/templates/files_fe_deploy.yaml
  apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
  apps/vault/config/cluster/deploy/vault_server_deploy.yaml
  apps/vault/config/user/helm-charts/vault/templates/vault_deploy.yaml
Labels: fix

#675 fix: update img size when onResize
  apps/files/config/user/helm-charts/files/templates/files_fe_deploy.yaml
  apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
  apps/vault/config/cluster/deploy/vault_server_deploy.yaml
  apps/vault/config/user/helm-charts/vault/templates/vault_deploy.yaml
Labels: fix

#678 fix: change system upgrade job image pull policy
  build/manifest/images
  frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
Labels: fix

#681 fix: nats auth error after upgrade
  frameworks/tapr/config/cluster/deploy/middleware_deploy.yaml
Labels: fix

#680 fix: choose nat ip as local domain dns record if present
  frameworks/bfl/config/launcher/templates/bfl_deploy.yaml
Labels: fix

#679 feat: set default nat gateway ip in prompt for mac
  build/installer/install.sh
Labels: feat
