Repository beclab/Olares, pull requests merged in 2024-12, with the labels that each got.

#682 feat: market-backend no local db & cache api data
  apps/market/config/user/helm-charts/market/templates/market_deploy.yaml
Labels: feat

#683 docs: update platform support info
  README.md
  README_CN.md
Labels: docs

#685 fix: Larepass v1.2.67
  apps/files/config/user/helm-charts/files/templates/files_fe_deploy.yaml
  apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
  apps/vault/config/cluster/deploy/vault_server_deploy.yaml
  apps/vault/config/user/helm-charts/vault/templates/vault_deploy.yaml
Labels: fix

#686 fix: external 404 when it is null fixed
  apps/files/config/cluster/deploy/files_deploy.yaml
Labels: fix

#687 feat: update knowledge to v0.1.54
  apps/download/config/user/helm-charts/download/templates/download_deploy.yaml
  apps/knowledge/config/user/helm-charts/knowledge/templates/knowledge_deployment.yaml
Labels: feat

#688 fix: get local IP by the default route
  build/installer/install.ps1
  build/installer/install.sh
Labels: fix

#689 feat: s3, dropbox async download and upload task
  apps/files/config/user/helm-charts/files/templates/files_fe_deploy.yaml
Labels: feat

#676 feat: add env for install.sh to choose between JuiceFS & local fs
  .gitignore
  build/installer/install.sh
Labels: feat

#691 feat: show progress info when downloading & importing
  build/installer/install.sh
Labels: feat

#690 feat: remove settings pod
  apps/settings/README.md
  apps/settings/config/user/helm-charts/settings/.helmignore
  apps/settings/config/user/helm-charts/settings/Chart.yaml
  apps/settings/config/user/helm-charts/settings/templates/NOTES.txt
  apps/settings/config/user/helm-charts/settings/templates/_helpers.tpl
  apps/settings/config/user/helm-charts/settings/templates/settings_deploy.yaml
  apps/settings/config/user/helm-charts/settings/values.yaml
  apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
Labels: feat

#692 fix: remove nitro
  apps/nitro/README.md
  apps/nitro/config/cluster/deploy/nitro_deploy.yaml
Labels: fix

#693 fix: bfl ingress http2
  frameworks/bfl/config/launcher/templates/bfl_deploy.yaml
Labels: fix

#694 fix: settings nginx conf bug
  apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
Labels: fix

#695 feat: upgrade search to v0.0.21, add chinese token type word to simpk…
  apps/search3/config/cluster/deploy/search3_server_deploy.yaml
Labels: feat

#696 fix: store & compare applied dns record of local domain
  frameworks/bfl/config/launcher/templates/bfl_deploy.yaml
Labels: fix

#697 fix: Update learpass to v1.2.69
  apps/files/config/user/helm-charts/files/templates/files_fe_deploy.yaml
  apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
  apps/vault/config/cluster/deploy/vault_server_deploy.yaml
  apps/vault/config/user/helm-charts/vault/templates/vault_deploy.yaml
Labels: fix

#698 fix: optimize log watching
  build/manifest/components
Labels: fix

#699 fix: update settings nginx gzip
  apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
Labels: fix

#700 fix: bfl ingress add application/x-mpegURL gzip types
  frameworks/bfl/config/launcher/templates/bfl_deploy.yaml
Labels: fix

#702 ci: build redis for glibc_2.31
  .github/workflows/build-redis-231.yaml
  scripts/build-redis.sh
Labels: ci

#701 feat: inject runasuser equal 1000 for third party app's pod
  frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
Labels: feat

#703 feat: During the wizard process, skip the step of choosing whether to enable reverse proxy.
  apps/wizard/config/user/helm-charts/wizard/templates/wizard_deploy.yaml
Labels: feat

#704 fix: Ubuntu 20.04 broken installation
  .github/PULL_REQUEST_TEMPLATE.md
  build/installer/install.ps1
  build/installer/install.sh
  build/manifest/components
Labels: fix

#705 chore: settings v0.1.95 add host address management
  apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
Labels: chore

#706 feat: upgrade search3 to v0.0.22, when detect short keyword language …
  apps/search3/config/cluster/deploy/search3_server_deploy.yaml
Labels: feat

#708 fix: find command nmcli
  build/manifest/components
Labels: fix

#709 feat: configure coreDNS to serve record from node /etc/hosts
  build/installer/install.sh
  build/manifest/images
Labels: feat

#707 fix: ignore system frontend
  build/manifest/images
  frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
Labels: fix

#710 fix: init without unicast ip
  build/manifest/components
Labels: fix

#712 feat: upgrade app-service upgrade job
  build/manifest/images
  frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
Labels: feat

#711 fix: wise video audio search missing
  apps/knowledge/config/user/helm-charts/knowledge/templates/knowledge_deployment.yaml
  apps/search3/config/cluster/deploy/search3_server_deploy.yaml
Labels: fix

#713 fix: revert runasuser
  apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
  build/manifest/images
  frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
Labels: fix

#714 feat: all language search use simple config map
  apps/search3/config/cluster/deploy/search3_server_deploy.yaml
Labels: feat

#716 feat: add control-hub middleware
  apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
Labels: feat

#717 feat: add control-hub middleware 1.10
  apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
Labels: feat
