Repository beclab/Olares, pull requests merged in 2024-06, with the labels that each got.

#104 feat: configurable using NITRO or WASM
  apps/nitro/config/cluster/deploy/dify_deploy.yaml
Labels: feat

#106 fix: add new badges and fix wording
  README.md
Labels: fix

#107 fix: progress job use random ticker to lower conflict
  frameworks/app-service/config/cluster/crds/app.bytetrade.io_imagemanagers.yaml
  frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
Labels: fix

#111 fix: increase mongodb resource limit
  frameworks/tapr/config/cluster/deploy/mongodb_deployment.yaml
Labels: fix

#109 fix: files paste timeout
  apps/files/config/user/helm-charts/files/templates/files_deploy.yaml
Labels: fix

#113 fix: support deletion operations for oss during uninstallation
  build/installer/uninstall_cmd.sh
Labels: fix

#114 feat: add retry to refresh sts token
  frameworks/osnode-init/config/cluster/deploy/nodeinit_daemonset.yaml
Labels: feat

#115 fix: controlHub middleware list
  apps/system-apps/config/user/helm-charts/system/templates/admin_console_deploy.yaml
Labels: fix

#116 fix: control-hub workloads
  apps/system-apps/config/user/helm-charts/system/templates/admin_console_deploy.yaml
Labels: fix

#117 feat: postgresql support extension and execute script;mongo support execute script
  apps/argo/config/user/helm-charts/argo/templates/argo_deployment.yaml
  frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
  frameworks/tapr/config/cluster/crds/apr.bytetrade.io_middlewarerequests.yaml
  frameworks/tapr/config/cluster/crds/apr.bytetrade.io_pgclusters.yaml
  frameworks/tapr/config/cluster/deploy/middleware_deploy.yaml
  third-party/infisical/config/user/helm-charts/infisical/templates/infisical_deploy.yaml
Labels: feat

#119 fix: velero image pull timeout causing k3s installation failure
  build/installer/install_cmd.sh
  build/manifest/images
Labels: fix

#120 fix: use the release version got from Terminus Space to upgrade the OS.
  frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
Labels: fix

#122 feat: Desktop and login add ways to open mobile browser bookmarks
  apps/desktop/config/user/helm-charts/desktop/templates/desktop_deploy.yaml
  third-party/authelia/config/user/helm-charts/auth/templates/auth_deploy.yaml
Labels: feat

#121 feat: Desktop and login add ways to open mobile browser bookmarks
  apps/desktop/config/user/helm-charts/desktop/templates/desktop_deploy.yaml
  third-party/authelia/config/user/helm-charts/auth/templates/auth_deploy.yaml
Labels: feat

#123 ci: upload the full package to s3 in daily-build
  .github/workflows/release-daily.yaml
  build/installer/publicInstaller.sh
Labels: ci

#125 feat: add kvrocks to cluster as Redis Cluster alternative
  frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
  frameworks/tapr/config/cluster/crds/apr.bytetrade.io_kvrocksbackups.yaml
  frameworks/tapr/config/cluster/crds/apr.bytetrade.io_kvrocksrestores.yaml
  frameworks/tapr/config/cluster/crds/apr.bytetrade.io_redixclusters.yaml
  frameworks/tapr/config/cluster/deploy/middleware_deploy.yaml
  frameworks/tapr/config/cluster/deploy/rediscluster_deploy.yaml
  frameworks/tapr/config/cluster/deploy/redixcluster_deploy.yaml
Labels: feat

#126 fix: remove seafile ui and add dify auth
  apps/nitro/config/user/helm-charts/dify/templates/dify_fe_deploy.yaml
  third-party/seahub/config/user/helm-charts/seafile/templates/seafile_fe_deploy.yaml
Labels: fix

#127 fix: remove seafile ui and add dify auth
  apps/nitro/config/user/helm-charts/dify/templates/dify_fe_deploy.yaml
  third-party/seahub/config/user/helm-charts/seafile/templates/seafile_fe_deploy.yaml
Labels: fix

#128 feat: upgrade infisical following the official latest version
  third-party/infisical/config/user/helm-charts/infisical/templates/infisical_deploy.yaml
Labels: feat

#129 fix: add infisical deployment init-container envs
  build/installer/version.hint
  third-party/infisical/config/user/helm-charts/infisical/templates/infisical_deploy.yaml
Labels: fix

#131 fix: nitro relative bugs
  apps/agent/config/user/helm-charts/agent/templates/agent_deploy.yaml
  apps/nitro/config/cluster/deploy/dify_deploy.yaml
Labels: fix

#130 fix: nitro relative bugs
  apps/agent/config/user/helm-charts/agent/templates/agent_deploy.yaml
  apps/nitro/config/cluster/deploy/dify_deploy.yaml
Labels: fix

#132 ci: add installing test
  .github/workflows/check.yaml
Labels: ci

#133 feat: argo change pg
  apps/argo/config/user/helm-charts/argo/charts/argoworkflows/templates/server/server-deployment.yaml
  apps/argo/config/user/helm-charts/argo/templates/argo_deployment.yaml
Labels: feat

#134 feat: knowledge replace mongo with pg
  apps/knowledge/config/user/helm-charts/knowledge/templates/knowledge_deployment.yaml
  apps/wise/config/user/helm-charts/wise/templates/wise_deployment.yaml
Labels: feat

#136 feat: dark theme main
  apps/market/config/user/helm-charts/market/templates/market_deploy.yaml
  apps/profile/config/user/helm-charts/profile/templates/profile_deployment.yaml
  apps/settings/config/user/helm-charts/settings/templates/settings_deploy.yaml
  apps/system-apps/config/user/helm-charts/monitoring/templates/monitoring_deploy.yaml
  apps/system-apps/config/user/helm-charts/system/templates/admin_console_deploy.yaml
Labels: feat

#138 feat: save terminus data in a separate disk
  build/installer/install_cmd.sh
Labels: feat

#137 feat: remove mongodb installing by default
  build/installer/version.hint
  frameworks/tapr/config/cluster/deploy/fakes3_deployment.yaml
  frameworks/tapr/config/cluster/deploy/mongodb_deployment.yaml
Labels: feat

#139 feat: update settings and desktop support dark theme
  apps/desktop/config/user/helm-charts/desktop/templates/desktop_deploy.yaml
  apps/files/config/user/helm-charts/files/templates/files_deploy.yaml
  apps/settings/config/user/helm-charts/settings/templates/settings_deploy.yaml
  apps/vault/config/cluster/deploy/vault_server_deploy.yaml
  apps/vault/config/user/helm-charts/vault/templates/vault_deploy.yaml
Labels: feat

#140 feat: update settings/desktop/vault/files support dark theme
  apps/desktop/config/user/helm-charts/desktop/templates/desktop_deploy.yaml
  apps/files/config/user/helm-charts/files/templates/files_deploy.yaml
  apps/settings/config/user/helm-charts/settings/templates/settings_deploy.yaml
  apps/vault/config/cluster/deploy/vault_server_deploy.yaml
  apps/vault/config/user/helm-charts/vault/templates/vault_deploy.yaml
Labels: feat

#141 feat: add controlhub service configmaps secrets yaml editor
  apps/system-apps/config/user/helm-charts/system/templates/admin_console_deploy.yaml
Labels: feat

#143 feat: Devbox adds dark theme
  apps/devbox/config/user/helm-charts/devbox/templates/deployment.yaml
Labels: feat

#142 feat: Devbox adds dark theme
  apps/devbox/config/user/helm-charts/devbox/templates/deployment.yaml
Labels: feat

#145 feat: tailscale support arm64
  third-party/headscale/config/user/helm-charts/headscale/templates/headscale_deploy.yaml
Labels: feat

#146 feat: citus arm64 supported
  frameworks/tapr/config/cluster/deploy/citus_deployment.yaml
Labels: feat

#147 feat: User Group (Control Hub/Browse)
  apps/system-apps/config/cluster/deploy/ks_server_deploy.yaml
  apps/system-apps/config/user/helm-charts/monitoring/templates/monitoring_deploy.yaml
  apps/system-apps/config/user/helm-charts/system/templates/admin_console_deploy.yaml
Labels: feat

#150 feat: update files vault settings profile new version support arm
  apps/files/config/user/helm-charts/files/templates/files_deploy.yaml
  apps/profile/config/user/helm-charts/profile/templates/profile_deployment.yaml
  apps/settings/config/user/helm-charts/settings/templates/settings_deploy.yaml
  apps/vault/config/cluster/deploy/vault_server_deploy.yaml
  apps/vault/config/user/helm-charts/vault/templates/vault_deploy.yaml
Labels: feat

#149 feat: seafile/files/dify/nitro arm64 support
  apps/agent/config/user/helm-charts/agent/templates/agent_deploy.yaml
  apps/files/config/user/helm-charts/files/templates/files_deploy.yaml
  apps/nitro/config/cluster/deploy/dify_deploy.yaml
  third-party/seahub/config/cluster/deploy/seafile_deploy.yaml
Labels: feat

#148 feat: support middleware install;set namespace for app
  apps/devbox/README.md
  apps/devbox/config/user/helm-charts/devbox/.helmignore
  apps/devbox/config/user/helm-charts/devbox/Chart.yaml
  apps/devbox/config/user/helm-charts/devbox/devbox.png
  apps/devbox/config/user/helm-charts/devbox/templates/deployment.yaml
  apps/devbox/config/user/helm-charts/devbox/values.yaml
  apps/market/config/user/helm-charts/market/templates/market_deploy.yaml
  build/installer/install_cmd.sh
  frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
Labels: feat

#151 fix: rm no usage middlewarerequest of mongodb
  apps/argo/config/user/helm-charts/argo/templates/argo_deployment.yaml
Labels: fix

#152 feat: only nitro and nginx in nitro now
  apps/nitro/config/cluster/deploy/dify_deploy.yaml
  frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
Labels: feat

#156 fix: velero image pull timeout
  build/installer/install_cmd.sh
Labels: fix

#153 fix: nitro-dedify yaml bug
  apps/nitro/config/cluster/deploy/dify_deploy.yaml
Labels: fix

#154 fix: add applicationmanagers,imagemanagers permission for workspaces-manager role
  build/installer/install_cmd.sh
  build/installer/uninstall_cmd.sh
  build/manifest/dependencies
Labels: fix

#155 fix: seahub tags not found bug
  third-party/seahub/config/cluster/deploy/seafile_deploy.yaml
Labels: fix

#157 feat: delete agent for the time being
  apps/agent/README.md
  apps/agent/config/user/helm-charts/agent/.helmignore
  apps/agent/config/user/helm-charts/agent/Chart.yaml
  apps/agent/config/user/helm-charts/agent/templates/NOTES.txt
  apps/agent/config/user/helm-charts/agent/templates/_helpers.tpl
  apps/agent/config/user/helm-charts/agent/templates/agent_deploy.yaml
  apps/agent/config/user/helm-charts/agent/values.yaml
Labels: feat

#158 fix: keep dify-ui in built-in apps
  frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
Labels: fix

#159 fix: make the dify-ui entrance invisible
  apps/nitro/config/user/helm-charts/dify/templates/dify_fe_deploy.yaml
Labels: fix

#160 fix: remove agent from appservice
  frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
Labels: fix

#164 fix: update ControlHub/CRDs yaml button text in UI
  apps/system-apps/config/user/helm-charts/system/templates/admin_console_deploy.yaml
Labels: fix

#163 fix: remove dify provider from files, dify model from nitro, aboveos in appdata and dify ui for the time being
  apps/files/config/user/helm-charts/files/templates/files_deploy.yaml
  apps/nitro/config/cluster/deploy/dify_deploy.yaml
  apps/nitro/config/user/helm-charts/dify/templates/dify_fe_deploy.yaml
Labels: fix

#165 feat: experimental version of arm64
  apps/desktop/config/user/helm-charts/desktop/templates/desktop_deploy.yaml
  apps/files/config/user/helm-charts/files/templates/files_deploy.yaml
  apps/market/config/user/helm-charts/market/templates/market_deploy.yaml
  apps/notifications/config/user/helm-charts/notification/templates/notification_deploy.yaml
  apps/profile/config/user/helm-charts/profile/templates/profile_deployment.yaml
  apps/settings/config/user/helm-charts/settings/templates/settings_deploy.yaml
  apps/system-apps/config/user/helm-charts/monitoring/templates/monitoring_deploy.yaml
  apps/system-apps/config/user/helm-charts/system/templates/admin_console_deploy.yaml
  apps/vault/config/user/helm-charts/vault/templates/vault_deploy.yaml
  apps/wise/config/user/helm-charts/wise/templates/wise_deployment.yaml
  apps/wizard/config/user/helm-charts/wizard/templates/wizard_deploy.yaml
  build/installer/install_cmd.sh
  build/installer/uninstall_cmd.sh
  build/manifest/dependencies.amd64
  build/manifest/dependencies.arm64
  build/manifest/images
  frameworks/system-server/config/user/helm-charts/systemserver/templates/systemserver_deploy.yaml
  scripts/build-full.sh
  scripts/build.sh
  scripts/deps-manifest.sh
  scripts/developer/cluster-configuration.yaml
  scripts/developer/install_macos.sh
  scripts/developer/kubesphere-installer.yaml
  scripts/developer/uninstall_macos.sh
  scripts/download-deps.sh
  scripts/save-deps.sh
  scripts/save-images.sh
  scripts/upload-deps.sh
  scripts/upload-images.sh
  third-party/authelia/config/cluster/deploy/auth_backend_deploy.yaml
  third-party/headscale/config/user/helm-charts/headscale/templates/headscale_deploy.yaml
Labels: feat

#166 fix: files & nginx-lua arm64 support bug
  apps/files/config/user/helm-charts/files/templates/files_deploy.yaml
  apps/nitro/config/cluster/deploy/dify_deploy.yaml
  third-party/seahub/config/cluster/deploy/seafile_deploy.yaml
Labels: fix

#167 feat: l4 proxy & bfl ingress arm64 supported
  frameworks/bfl/config/launcher/templates/bfl_deploy.yaml
Labels: feat

#170 feat: update rss backend version
  apps/argo/config/user/helm-charts/argo/charts/argoworkflows/templates/server/server-deployment.yaml
  apps/knowledge/config/user/helm-charts/knowledge/templates/knowledge_deployment.yaml
Labels: feat

#169 feat: update wise version
  apps/knowledge/config/user/helm-charts/knowledge/templates/knowledge_deployment.yaml
  apps/wise/config/user/helm-charts/wise/templates/wise_deployment.yaml
Labels: feat

#168 fix: release version check bug
  build/installer/install_cmd.sh
Labels: fix
